import type { TeamTemplate } from './types';

/**
 * Built-in team blueprints.
 * No agentIds — users assign actual agents to each slot in the builder.
 */
export const TEAM_TEMPLATES: TeamTemplate[] = [
  {
    id: 'content-pipeline',
    name: 'Content Pipeline',
    description: 'Research → draft → edit → publish-ready article.',
    routingStrategy: 'sequential',
    config: { outputFormat: 'markdown', maxSteps: 4 },
    memberSlots: [
      {
        displayRole: 'Orchestrator',
        role: 'orchestrator',
        tags: [],
        position: 0,
        slotHint: 'General-purpose orchestrator agent',
      },
      {
        displayRole: 'Researcher',
        role: 'specialist',
        tags: ['research', 'data'],
        position: 1,
        slotHint: 'Agent with web-search or knowledge-base tools enabled',
      },
      {
        displayRole: 'Writer',
        role: 'specialist',
        tags: ['copy', 'content'],
        position: 2,
        slotHint: 'Creative writing agent',
      },
      {
        displayRole: 'Editor',
        role: 'specialist',
        tags: ['content'],
        position: 3,
        slotHint: 'Editing and QA agent',
      },
    ],
  },
  {
    id: 'marketing-campaign',
    name: 'Marketing Campaign',
    description: 'Audience research → strategy → copy → creative direction.',
    routingStrategy: 'planner_generated',
    config: { outputFormat: 'markdown', maxSteps: 5 },
    memberSlots: [
      {
        displayRole: 'Orchestrator',
        role: 'orchestrator',
        tags: [],
        position: 0,
        slotHint: 'General-purpose orchestrator agent',
      },
      {
        displayRole: 'Researcher',
        role: 'specialist',
        tags: ['research', 'data'],
        position: 1,
        slotHint: 'Agent with web-search tools for market research',
      },
      {
        displayRole: 'Strategist',
        role: 'specialist',
        tags: ['strategy'],
        position: 2,
        slotHint: 'Marketing strategy or brand positioning agent',
      },
      {
        displayRole: 'Copywriter',
        role: 'specialist',
        tags: ['ad_copy', 'copy'],
        position: 3,
        slotHint: 'Ad copy and campaign messaging agent',
      },
      {
        displayRole: 'Creative Director',
        role: 'specialist',
        tags: ['creative_direction', 'design'],
        position: 4,
        slotHint: 'Visual concept and creative direction agent',
      },
    ],
  },
  {
    id: 'product-discovery',
    name: 'Product Discovery',
    description: 'Market scan → user needs → feature prioritisation.',
    routingStrategy: 'planner_generated',
    config: { outputFormat: 'markdown', maxSteps: 4 },
    memberSlots: [
      {
        displayRole: 'Orchestrator',
        role: 'orchestrator',
        tags: [],
        position: 0,
        slotHint: 'General-purpose orchestrator agent',
      },
      {
        displayRole: 'Researcher',
        role: 'specialist',
        tags: ['research', 'data'],
        position: 1,
        slotHint: 'User research or market analysis agent',
      },
      {
        displayRole: 'PM Analyst',
        role: 'specialist',
        tags: ['analysis', 'strategy'],
        position: 2,
        slotHint: 'Product management and prioritisation agent',
      },
      {
        displayRole: 'Solution Designer',
        role: 'specialist',
        tags: ['strategy', 'content'],
        position: 3,
        slotHint: 'Product solution framing and feature specification agent',
      },
    ],
  },
  {
    id: 'repurposing-engine',
    name: 'Repurposing Engine',
    description: 'Transform a single piece of content into blog post, social posts, email, and ad copy.',
    routingStrategy: 'planner_generated',
    config: { outputFormat: 'markdown', maxSteps: 6 },
    memberSlots: [
      {
        displayRole: 'Orchestrator',
        role: 'orchestrator',
        tags: [],
        position: 0,
        slotHint: 'General-purpose orchestrator agent',
      },
      {
        displayRole: 'Content Analyst',
        role: 'specialist',
        tags: ['analysis', 'content'],
        position: 1,
        slotHint: 'Analyzes source content and extracts key messages, themes, and audience insights',
      },
      {
        displayRole: 'Long-form Writer',
        role: 'specialist',
        tags: ['content'],
        position: 2,
        slotHint: 'Rewrites as SEO-optimized blog post or newsletter',
      },
      {
        displayRole: 'Social Copywriter',
        role: 'specialist',
        tags: ['copy', 'ad_copy'],
        position: 3,
        slotHint: 'Creates LinkedIn post, tweet thread, and social captions',
      },
      {
        displayRole: 'Email Writer',
        role: 'specialist',
        tags: ['copy', 'content'],
        position: 4,
        slotHint: 'Adapts content to email format with compelling subject lines',
      },
      {
        displayRole: 'Creative Director',
        role: 'specialist',
        tags: ['creative_direction'],
        position: 5,
        slotHint: 'Generates image prompts and ad creative angles',
      },
    ],
  },
  {
    id: 'campaign-brief-generator',
    name: 'Campaign Brief Generator',
    description: 'Research → brand strategy → structured campaign brief.',
    routingStrategy: 'planner_generated',
    config: { outputFormat: 'markdown', maxSteps: 4 },
    memberSlots: [
      {
        displayRole: 'Orchestrator',
        role: 'orchestrator',
        tags: [],
        position: 0,
        slotHint: 'General-purpose orchestrator agent',
      },
      {
        displayRole: 'Market Researcher',
        role: 'specialist',
        tags: ['research', 'data'],
        position: 1,
        slotHint: 'Agent with web-search tools for audience and competitor research',
      },
      {
        displayRole: 'Brand Strategist',
        role: 'specialist',
        tags: ['strategy'],
        position: 2,
        slotHint: 'Maps research to brand positioning and ICP insights',
      },
      {
        displayRole: 'Brief Writer',
        role: 'specialist',
        tags: ['content', 'copy'],
        position: 3,
        slotHint: 'Synthesizes findings into a structured campaign brief',
      },
    ],
  },
  {
    id: 'support-triage',
    name: 'Support Triage',
    description: 'Classify → diagnose → draft resolution → escalate if needed.',
    routingStrategy: 'sequential',
    config: { outputFormat: 'markdown', maxSteps: 4 },
    memberSlots: [
      {
        displayRole: 'Orchestrator',
        role: 'orchestrator',
        tags: [],
        position: 0,
        slotHint: 'General-purpose orchestrator agent',
      },
      {
        displayRole: 'Classifier',
        role: 'specialist',
        tags: ['analysis'],
        position: 1,
        slotHint: 'Issue classification and intent detection agent',
      },
      {
        displayRole: 'Policy Checker',
        role: 'specialist',
        tags: ['analysis', 'research'],
        position: 2,
        slotHint: 'Agent with access to policy/knowledge-base documents',
      },
      {
        displayRole: 'Response Drafter',
        role: 'specialist',
        tags: ['content', 'copy'],
        position: 3,
        slotHint: 'Customer response writing agent',
      },
    ],
  },
];
