import type { ModelDefinition } from "@/types/execution";

/**
 * KIE.ai image generation models.
 *
 * Each model has an `imageOptions` block — the single source of truth for:
 *  - which mode the model supports (generate / edit / both)
 *  - which aspect ratios it accepts
 *  - which UI controls to show (quality, resolution, seed, google search)
 *  - display metadata (iconProvider, badge, creditCost)
 *
 * `features/image/types.ts` derives IMAGE_MODEL_CONFIGS from this list.
 * Adding a new model = add one entry here. No other files need to change.
 */
export const KIE_IMAGE_MODELS: ModelDefinition[] = [
  // ─── Nano Banana ────────────────────────────────────────────────────────────
  {
    id: "nano-banana-2",
    name: "Nano Banana 2",
    description:
      "Experience Google's Gemini 3.1 Flash Image technology featuring 4K generation, lightning-fast speeds, and perfect character consistency for developers.",
    capabilities: ["image"],
    provider: "kie",
    costPerGeneration: 8,
    isNew: true,
    maxPromptLength: 20000,
    maxPromptTokens: 5000,
    warningThreshold: 0.8,
    guestAccess: true,
    maxReferenceImages: 14,
    referenceImageParam: "image_input",
    imageOptions: {
      mode: "both",
      aspectRatios: [
        "auto",
        "1:1",
        "1:4",
        "1:8",
        "2:3",
        "3:2",
        "3:4",
        "4:1",
        "4:3",
        "4:5",
        "5:4",
        "8:1",
        "9:16",
        "16:9",
        "21:9",
      ],
      hasResolution: true,
      hasGoogleSearch: true,
      iconProvider: "kie",
      badge: "Popular",
      pricingTiers: {
        param: "resolution",
        map: { "1K": 8, "2K": 12, "4K": 18 },
        default: "1K",
      },
    },
  },
  {
    id: "nano-banana-pro",
    name: "Nano Banana Pro",
    description:
      "Gemini 3 Pro — flawless text rendering, 4K resolution, up to 8 reference images",
    capabilities: ["image"],
    provider: "kie",
    costPerGeneration: 18,
    isNew: false,
    maxPromptLength: 20000,
    maxPromptTokens: 5000,
    warningThreshold: 0.8,
    maxReferenceImages: 8,
    referenceImageParam: "image_input",
    imageOptions: {
      mode: "both",
      aspectRatios: [
        "auto",
        "1:1",
        "16:9",
        "9:16",
        "4:3",
        "3:4",
        "2:3",
        "3:2",
        "21:9",
        "4:5",
        "5:4",
      ],
      hasResolution: true,
      iconProvider: "kie",
      badge: "Premium",
      pricingTiers: {
        param: "resolution",
        map: { "1K": 18, "2K": 18, "4K": 24 },
        default: "1K",
      },
    },
  },

  // ─── GPT Image ──────────────────────────────────────────────────────────────
  {
    id: "gpt-image-2-text-to-image",
    name: "GPT Image 2 text to image",
    description: "GPT Image 2 is OpenAI’s next-gen image model built for stronger photorealism, cleaner image editing, sharper text rendering, and more polished product photography. Designed for more advanced visual workflows, it pushes image generation beyond basic text-to-image output and into higher-quality creative, commercial, and design-ready use cases.",
    capabilities: ["image"],
    provider: "kie",
    costPerGeneration: 12,
    isNew: true,
    maxPromptLength: 20000,
    maxPromptTokens: 5000,
    warningThreshold: 0.8,
    maxReferenceImages: 0,
    imageOptions: {
      mode: "generate",
      iconProvider: "openai",
      badge: "Photorealistic",
    },
  },
  {
    id: "gpt-image-2-image-to-image",
    name: "GPT Image 2 image to image",
    description: "GPT Image 2 is OpenAI’s next-gen image model built for stronger photorealism, cleaner image editing, sharper text rendering, and more polished product photography. Designed for more advanced visual workflows, it pushes image generation beyond basic text-to-image output and into higher-quality creative, commercial, and design-ready use cases.",
    capabilities: ["image"],
    provider: "kie",
    costPerGeneration: 12,
    isNew: true,
    maxPromptLength: 20000,
    maxPromptTokens: 5000,
    warningThreshold: 0.8,
    maxReferenceImages: 10,
    referenceImageParam: "input_urls",
    requiresReferenceImages: true,
    imageOptions: {
      mode: "edit",
      aspectRatios: ["auto", "1:1", "5:4", "9:16", "21:9", "16:9", "4:3", "3:2", "2:3"],
      requiresImages: true,
      iconProvider: "openai",
      badge: "Photorealistic",
    },
  },
  {
    id: "gpt-image/1.5-text-to-image",
    name: "GPT Image 1.5",
    description: "Photorealistic generation with quality control",
    capabilities: ["image"],
    provider: "kie",
    costPerGeneration: 4,
    isNew: true,
    maxPromptLength: 3000,
    maxPromptTokens: 1500,
    warningThreshold: 0.8,
    maxReferenceImages: 0,
    imageOptions: {
      mode: "generate",
      aspectRatios: ["1:1", "2:3", "3:2"],
      hasQuality: true,
      iconProvider: "openai",
      badge: "Photorealistic",
      pricingTiers: {
        param: "quality",
        map: { medium: 4, high: 22 },
        default: "medium",
      },
    },
  },
  {
    id: "gpt-image/1.5-image-to-image",
    name: "GPT Image 1.5 image",
    description: "Identity-preserving image edits with quality control",
    capabilities: ["image"],
    provider: "kie",
    costPerGeneration: 4,
    isNew: true,
    maxPromptLength: 3000,
    maxPromptTokens: 1500,
    warningThreshold: 0.8,
    maxReferenceImages: 10,
    referenceImageParam: "input_urls",
    requiresReferenceImages: true,
    imageOptions: {
      mode: "edit",
      aspectRatios: ["1:1", "2:3", "3:2"],
      hasQuality: true,
      requiresImages: true,
      iconProvider: "openai",
      badge: "Precise Edit",
      pricingTiers: {
        param: "quality",
        map: { medium: 4, high: 22 },
        default: "medium",
      },
    },
  },

  // ─── Seedream 5 Lite ────────────────────────────────────────────────────────
  {
    id: "seedream/5-lite-text-to-image",
    name: "Seedream 5 Lite",
    description:
      "ByteDance — 4K generation, precise editing, consistent multi-image output",
    capabilities: ["image"],
    provider: "kie",
    costPerGeneration: 4,
    isNew: true,
    maxPromptLength: 3000,
    maxPromptTokens: 1500,
    warningThreshold: 0.8,
    maxReferenceImages: 0,
    imageOptions: {
      mode: "generate",
      aspectRatios: ["1:1", "4:3", "3:2", "3:4", "16:9", "9:16", "2:3", "21:9"],
      iconProvider: "bytedance",
      badge: "New",
      creditCost: 4,
    },
  },
  {
    id: "seedream/5-lite-image-to-image",
    name: "Seedream 5 Lite Edit",
    description: "ByteDance — image-to-image with 4K output",
    capabilities: ["image"],
    provider: "kie",
    costPerGeneration: 4,
    isNew: true,
    maxPromptLength: 3000,
    maxPromptTokens: 1500,
    warningThreshold: 0.8,
    maxReferenceImages: 10,
    referenceImageParam: "input_urls",
    requiresReferenceImages: true,
    imageOptions: {
      mode: "edit",
      aspectRatios: ["1:1", "4:3", "3:2", "3:4", "16:9", "9:16", "2:3", "21:9"],
      requiresImages: true,
      iconProvider: "bytedance",
      badge: "New",
      creditCost: 4,
    },
  },

  // ─── Qwen ───────────────────────────────────────────────────────────────────
  {
    id: "qwen2/text-to-image",
    name: "Qwen2 Text to Image",
    description:
      "Open-source text-to-image, excellent bilingual text rendering",
    capabilities: ["image"],
    provider: "kie",
    costPerGeneration: 3,
    isNew: true,
    maxPromptLength: 5000,
    maxPromptTokens: 1500,
    warningThreshold: 0.8,
    guestAccess: true,
    maxReferenceImages: 0,
    imageOptions: {
      mode: "generate",
      aspectRatios: ["1:1", "4:3", "3:4", "16:9", "9:16"],
      aspectRatioParam: "image_size",
      hasSeed: true,
      iconProvider: "qwen",
      creditCost: 3,
    },
  },
  {
    id: "qwen2/image-edit",
    name: "Qwen2 Image Edit",
    description: "Open-source image editing with seed for reproducibility",
    capabilities: ["image"],
    provider: "kie",
    costPerGeneration: 3,
    isNew: true,
    maxPromptLength: 800,
    maxPromptTokens: 250,
    warningThreshold: 0.8,
    maxReferenceImages: 10,
    referenceImageParam: "image_url",
    requiresReferenceImages: true,
    imageOptions: {
      mode: "edit",
      aspectRatios: ["1:1", "2:3", "3:2", "3:4", "4:3", "9:16", "16:9", "21:9"],
      aspectRatioParam: "image_size",
      hasSeed: true,
      requiresImages: true,
      iconProvider: "qwen",
      creditCost: 3,
    },
  },
  {
    id: "z-image",
    name: "Qwen Z-Image",
    description: "Fast and affordable, excellent bilingual text rendering",
    capabilities: ["image"],
    provider: "kie",
    costPerGeneration: 1,
    isNew: false,
    maxPromptLength: 5000,
    maxPromptTokens: 1250,
    warningThreshold: 0.8,
    guestAccess: true,
    maxReferenceImages: 0,
    imageOptions: {
      mode: "generate",
      aspectRatios: ["1:1", "4:3", "3:4", "16:9", "9:16"],
      aspectRatioParam: "aspect_ratio",
      iconProvider: "qwen",
      badge: "Fast",
      creditCost: 1,
    },
  },

  // ─── Grok / xAI ─────────────────────────────────────────────────────────────
  {
    id: "grok-imagine/text-to-image",
    name: "Grok Imagine",
    description: "xAI's creative and expressive image generation",
    capabilities: ["image"],
    provider: "kie",
    costPerGeneration: 4,
    isNew: true,
    maxPromptLength: 5000,
    maxPromptTokens: 1250,
    warningThreshold: 0.8,
    maxReferenceImages: 0,
    imageOptions: {
      mode: "generate",
      aspectRatios: ["2:3", "3:2", "1:1", "9:16", "16:9"],
      hasEnablePro: true,
      iconProvider: "xai",
      badge: "New",
      creditCost: 4,
    },
  },
  {
    id: "grok-imagine/image-to-image",
    name: "Grok Imagine Edit",
    description: "xAI image-to-image generation using a reference image",
    capabilities: ["image"],
    provider: "kie",
    costPerGeneration: 4,
    isNew: true,
    maxPromptLength: 390000,
    maxPromptTokens: 97500,
    warningThreshold: 0.8,
    maxReferenceImages: 1,
    referenceImageParam: "image_urls",
    requiresReferenceImages: true,
    imageOptions: {
      mode: "edit",
      aspectRatios: ["auto"],
      hasEnablePro: true,
      requiresImages: true,
      iconProvider: "xai",
      badge: "New",
      creditCost: 4,
    },
  },
];
